on:
  pull_request:
  repository_dispatch:
    types: [ok-to-test-command]
name: Unit tests

jobs:
  unit:
    if: 
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.sha != '' &&
      contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - check-docs
          - test
          - test-acceptance
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make setup
      - name: make ${{ matrix.target }}
        run: make ${{ matrix.target }}
        env:
          DBT_CLOUD_ACCOUNT_ID: ${{ secrets.TEST_DBT_CLOUD_ACCOUNT_ID }}
          DBT_CLOUD_TOKEN: ${{ secrets.TEST_DBT_CLOUD_TOKEN }}
